apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: kubeverse-my-application
  labels:
    app: backend
    app.kubernetes.io/managed-by: kubeverse
    kubeverse.dev/project-id: 01a037bf-5bff-7285-a0d0-0d8e79272479
    kubeverse.dev/project-name: TEST-001
spec:
  selector:
    app: backend
  ports:
    - port: 4000
      targetPort: 4000
  type: ClusterIP
