// Deterministic template generator for runtime:'node' services. The AI never
// writes this code - KubeVerse does, from the validated NAM, so output is
// reproducible and inspectable (KUBEVERSE_MASTER_SPEC.md, "Inspectability over magic").
import type { ArchitectureSpec, ServiceSpec } from '../architecture/schema.js';
import { isManagedRuntime } from './managedService.js';
import type { GeneratedFile } from './types.js';

function dependencyEnvName(serviceName: string): string {
  return `${serviceName.replace(/-/g, '_').toUpperCase()}_URL`;
}

// A dependency is either another generated `node` service (speaks real
// HTTP, so /health is meaningful) or a managed runtime (mongodb/redis/
// postgres/mysql - speaks its own wire protocol, never HTTP). Checking
// managed deps with an HTTP fetch always reports 'unreachable' and spams the
// dependency's own logs (confirmed live: Redis logs "Possible SECURITY
// ATTACK detected" on an HTTP request) - a raw TCP connect is the honest
// check for those.
function dependencyStatusRoute(service: ServiceSpec, spec: ArchitectureSpec): string {
  if (service.dependsOn.length === 0) return '';
  let usesTcpCheck = false;
  const checks = service.dependsOn
    .map((dep) => {
      const envName = dependencyEnvName(dep);
      const target = spec.services.find((candidate) => candidate.name === dep);
      if (target && isManagedRuntime(target.runtime)) {
        usesTcpCheck = true;
        return `  results[${JSON.stringify(dep)}] = (await checkTcp(process.env.${envName})) ? 'reachable' : 'unreachable';`;
      }
      return `  try {\n    const response = await fetch(\`\${process.env.${envName}}/health\`);\n    results[${JSON.stringify(dep)}] = response.ok ? 'reachable' : \`status \${response.status}\`;\n  } catch {\n    results[${JSON.stringify(dep)}] = 'unreachable';\n  }`;
    })
    .join('\n');
  const tcpHelper = usesTcpCheck
    ? `function checkTcp(url) {\n  return new Promise((resolve) => {\n    const { hostname, port } = new URL(url);\n    const socket = net.createConnection({ host: hostname, port: Number(port), timeout: 2000 }, () => { socket.end(); resolve(true); });\n    socket.on('error', () => resolve(false));\n    socket.on('timeout', () => { socket.destroy(); resolve(false); });\n  });\n}\n\n`
    : '';
  return `\n${tcpHelper}app.get('/status', async (_req, res) => {\n  const results = {};\n${checks}\n  res.json({ service: SERVICE_NAME, dependencies: results });\n});\n`;
}

export function generateNodeService(service: ServiceSpec, spec: ArchitectureSpec): GeneratedFile[] {
  const packageJson = {
    name: service.name,
    private: true,
    type: 'module',
    version: '0.1.0',
    scripts: { start: 'node src/server.js' },
    dependencies: { express: '^4.19.2' },
  };

  const dependsOnManagedRuntime = service.dependsOn.some((dep) => {
    const target = spec.services.find((candidate) => candidate.name === dep);
    return target && isManagedRuntime(target.runtime);
  });

  const serverJs = `import express from 'express';${dependsOnManagedRuntime ? "\nimport net from 'node:net';" : ''}

const app = express();
app.use(express.json());

const PORT = process.env.PORT || ${service.port};
const SERVICE_NAME = ${JSON.stringify(service.name)};

app.get(${JSON.stringify(service.healthCheck.path)}, (_req, res) => res.json({ status: 'ok', service: SERVICE_NAME }));
app.get('/ready', (_req, res) => res.json({ status: 'ready', service: SERVICE_NAME }));

app.get('/', (_req, res) => {
  res.json({
    service: SERVICE_NAME,
    type: ${JSON.stringify(service.type)},
    dependsOn: ${JSON.stringify(service.dependsOn)},
    message: 'Generated by KubeVerse from architecture.md',
  });
});
${dependencyStatusRoute(service, spec)}
app.listen(PORT, () => {
  console.log(JSON.stringify({ level: 'info', service: SERVICE_NAME, msg: \`listening on port \${PORT}\` }));
});
`;

  const dockerfile = `FROM node:20-alpine
WORKDIR /app
COPY package.json ./
RUN npm install --omit=dev
COPY src ./src
ENV PORT=${service.port}
EXPOSE ${service.port}
CMD ["node", "src/server.js"]
`;

  const dependencyEnvLines = service.dependsOn
    .map((dep) => {
      const target = spec.services.find((candidate) => candidate.name === dep);
      return `${dependencyEnvName(dep)}=http://${dep}:${target?.port ?? 80}`;
    })
    .join('\n');

  const files: GeneratedFile[] = [
    { path: `${service.name}/package.json`, contents: `${JSON.stringify(packageJson, null, 2)}\n` },
    { path: `${service.name}/src/server.js`, contents: serverJs },
    { path: `${service.name}/Dockerfile`, contents: dockerfile },
  ];
  if (dependencyEnvLines) files.push({ path: `${service.name}/.env.example`, contents: `${dependencyEnvLines}\n` });
  return files;
}
