// Deterministic template generator for runtime:'node' services. The AI never
// writes this code - KubeVerse does, from the validated NAM, so output is
// reproducible and inspectable (KUBEVERSE_MASTER_SPEC.md, "Inspectability over magic").
import type { ArchitectureSpec, ServiceSpec } from '../architecture/schema.js';
import type { GeneratedFile } from './types.js';

function dependencyEnvName(serviceName: string): string {
  return `${serviceName.replace(/-/g, '_').toUpperCase()}_URL`;
}

function dependencyStatusRoute(service: ServiceSpec): string {
  if (service.dependsOn.length === 0) return '';
  const checks = service.dependsOn
    .map((dep) => {
      const envName = dependencyEnvName(dep);
      return `  try {\n    const response = await fetch(\`\${process.env.${envName}}/health\`);\n    results[${JSON.stringify(dep)}] = response.ok ? 'reachable' : \`status \${response.status}\`;\n  } catch {\n    results[${JSON.stringify(dep)}] = 'unreachable';\n  }`;
    })
    .join('\n');
  return `\napp.get('/status', async (_req, res) => {\n  const results = {};\n${checks}\n  res.json({ service: SERVICE_NAME, dependencies: results });\n});\n`;
}

export function generateNodeService(service: ServiceSpec, spec: ArchitectureSpec): GeneratedFile[] {
  const packageJson = {
    name: service.name,
    private: true,
    type: 'module',
    version: '0.1.0',
    scripts: { start: 'node src/server.js' },
    dependencies: { express: '^4.19.2' },
  };

  const serverJs = `import express from 'express';

const app = express();
app.use(express.json());

const PORT = process.env.PORT || ${service.port};
const SERVICE_NAME = ${JSON.stringify(service.name)};

app.get(${JSON.stringify(service.healthCheck.path)}, (_req, res) => res.json({ status: 'ok', service: SERVICE_NAME }));
app.get('/ready', (_req, res) => res.json({ status: 'ready', service: SERVICE_NAME }));

app.get('/', (_req, res) => {
  res.json({
    service: SERVICE_NAME,
    type: ${JSON.stringify(service.type)},
    dependsOn: ${JSON.stringify(service.dependsOn)},
    message: 'Generated by KubeVerse from architecture.md',
  });
});
${dependencyStatusRoute(service)}
app.listen(PORT, () => {
  console.log(JSON.stringify({ level: 'info', service: SERVICE_NAME, msg: \`listening on port \${PORT}\` }));
});
`;

  const dockerfile = `FROM node:20-alpine
WORKDIR /app
COPY package.json ./
RUN npm install --omit=dev
COPY src ./src
ENV PORT=${service.port}
EXPOSE ${service.port}
CMD ["node", "src/server.js"]
`;

  const dependencyEnvLines = service.dependsOn
    .map((dep) => {
      const target = spec.services.find((candidate) => candidate.name === dep);
      return `${dependencyEnvName(dep)}=http://${dep}:${target?.port ?? 80}`;
    })
    .join('\n');

  const files: GeneratedFile[] = [
    { path: `${service.name}/package.json`, contents: `${JSON.stringify(packageJson, null, 2)}\n` },
    { path: `${service.name}/src/server.js`, contents: serverJs },
    { path: `${service.name}/Dockerfile`, contents: dockerfile },
  ];
  if (dependencyEnvLines) files.push({ path: `${service.name}/.env.example`, contents: `${dependencyEnvLines}\n` });
  return files;
}
