name: My Application
networks:
  kubeverse: {}
services:
  frontend:
    build:
      context: ../generated/frontend
    ports:
      - 3000:3000
    networks:
      - kubeverse
  backend:
    build:
      context: ../generated/backend
    ports:
      - 4000:4000
    networks:
      - kubeverse
