apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: kubeverse-my-application
  labels:
    app: frontend
    app.kubernetes.io/managed-by: kubeverse
    kubeverse.dev/project-id: 01a037bf-5bff-7285-a0d0-0d8e79272479
    kubeverse.dev/project-name: TEST-001
spec:
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
